name: Azure Container Deployment - EliteDynamics

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure Container Registry login
      run: |
        az acr login --name elitedynamicsregistry

    - name: Build and push Docker image to ACR
      run: |
        docker build -t elitedynamicsregistry.azurecr.io/elitedynamicsapi:latest .
        docker push elitedynamicsregistry.azurecr.io/elitedynamicsapi:latest

    - name: Configure web app to use ACR image
      run: |
        az webapp config container set \
          --name elitedynamicsapi \
          --resource-group memorycognitiva \
          --docker-custom-image-name elitedynamicsregistry.azurecr.io/elitedynamicsapi:latest \
          --docker-registry-server-url https://elitedynamicsregistry.azurecr.io

    - name: Restart web app
      run: |
        az webapp restart --name elitedynamicsapi --resource-group memorycognitiva
