name: Deploy Python App to Azure Web App - EliteDynamicsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application
        run: |
          zip -r release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: elitedynamicsapi
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_795063DE34594158879BF4E0D0607C }}
          package: release.zip
